# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class He < Formula
  desc "HealthExport CLI - read and decrypt your health data"
  homepage "https://github.com/TParizek/healthexport_cli"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TParizek/healthexport_cli/releases/download/v1.0.0/he_1.0.0_darwin_amd64.tar.gz"
      sha256 "9bac122f01d4c6abd83c352574366ddc59291af0ef549590b9f4161db9b0b2de"

      define_method(:install) do
        bin.install "he"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TParizek/healthexport_cli/releases/download/v1.0.0/he_1.0.0_darwin_arm64.tar.gz"
      sha256 "4411c0e9b1a3104d5eed03fd98c538542246de1ca3b2821bd7b997355ff33633"

      define_method(:install) do
        bin.install "he"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TParizek/healthexport_cli/releases/download/v1.0.0/he_1.0.0_linux_amd64.tar.gz"
      sha256 "8781adbb636369c0fcb8933ab5c6161101be4501718597f72d0c0e2ee7c9e173"
      define_method(:install) do
        bin.install "he"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TParizek/healthexport_cli/releases/download/v1.0.0/he_1.0.0_linux_arm64.tar.gz"
      sha256 "a220c00c6d7e5b3ab5f3013d933624fd7950eeea9a267b98f9c97058c1c99ea2"
      define_method(:install) do
        bin.install "he"
      end
    end
  end

  test do
    system "#{bin}/he", "version"
  end
end
